### ISSUE TITLE
Add Support for Max Topic Claims

### ISSUE THREAD

**Issue by basharal** [dropbox/marshal#19]
In order to support load-balancing consumers that consume messages, but process them at their own pace, we need to limit the number of topics that can be claimed for a given marshal client-id when ClaimEntireTopic is specified.

**Comment by zorkian** [comment]
I would like to see this implemented in terms of being able to pass a list of topics to the `NewConsumer` function and having the Consumer object be able to handle multiple topics.

I'll get to this in the next week or two but someone is welcome to beat me to it.

**Comment by basharal** [comment]
This was fixed by https://github.com/dropbox/marshal/pull/29
