### ISSUE TITLE
Allow construction of consumer from an existing rationalizer

### ISSUE THREAD

**Issue by DrTall** [dropbox/marshal#40]
That is, let multiple Marshal consumers share a single rationalizer.

**Comment by zorkian** [comment]
Isn't this already true? `NewMarshaler` is the thing that creates/owns all the rationalizers, and `NewConsumer` just uses those to claim partitions etc.

**Comment by DrTall** [comment]
Haha I thought when we were on the whiteboard we agreed this needed doing, so I didn't actually verify before filing the ticket. :)

It may be that there is nothing to do here, let me see...

**Comment by DrTall** [comment]
The `NewMarshaler` makes you specify your topic and group id, so it needs to be refactored.

**Comment by zorkian** [comment]
Oh derp, that was the problem. Carry on!
 
--
Mark Smith
mark@qq.is
 
 
On Wed, May 11, 2016, at 09:31 AM, Sean wrote:
> The NewMarshaler makes you specify your topic and group id, so it
> needs to be refactored.
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub[1]
>
 

Links:

  1. https://github.com/dropbox/marshal/issues/40#issuecomment-218514680

**Comment by zorkian** [comment]
This was done.
