### ISSUE TITLE
Deadlock in call to marshal.Terminate from Consumer.tryClaimPartition

### ISSUE THREAD

**Issue by adamfaulkner** [dropbox/marshal#55]
This line calls marshal.Terminate while the lock is held (Lock)
marshal/consumer.go#L293

marshal.Terminate calls terminateAndCleanup, which calls terminateAndCleanup for all consumers:
marshal/marshal.go#L149

consumer.terminateAndCleanup attempts to acquire the lock (RLock)
marshal/consumer.go#L576

I think this blocks forever.

We discussed a bit offline, it should be sufficient to call marshal.Terminate from a separate goroutine. 

It would be nice to have a test for this code path -- that way we'll know for sure that it works and can correctly handle when this condition is reached in the code that uses this client.

**Comment by zorkian** [comment]
This was fixed, forgot to close.
